This dataset represents a sample of 5,000 senior secondary schools surveyed across different regions (Urban/Rural) and management types (Government/Private)

In [1]:
import pandas as pd

In [3]:
import numpy as np

In [5]:
import matplotlib.pyplot as plt

In [6]:
df = pd.read_csv('schools_science_combination_data.csv')

In [7]:
df

,School_Category,Location_Type,Management_Type,Total_Schools,Restricted_Streams_No_Guidance,Comprehensive_Streams_With_Guidance
0,Category A,Urban,Private,1500,350,1150
1,Category B,Urban,Government,1000,650,350
2,Category C,Rural,Private,1200,720,480
3,Category D,Rural,Government,1300,1050,250
4,Total,NaN,Total,5000,2770,2230

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 6 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   School_Category                      5 non-null      object
 1   Location_Type                        4 non-null      object
 2   Management_Type                      5 non-null      object
 3   Total_Schools                        5 non-null      int64
 4   Restricted_Streams_No_Guidance       5 non-null      int64
 5   Comprehensive_Streams_With_Guidance  5 non-null      int64
dtypes: int64(3), object(3)
memory usage: 372.0+ bytes

In [12]:
df.isnull()

,School_Category,Location_Type,Management_Type,Total_Schools,Restricted_Streams_No_Guidance,Comprehensive_Streams_With_Guidance
0,False,False,False,False,False,False
1,False,False,False,False,False,False
2,False,False,False,False,False,False
3,False,False,False,False,False,False
4,False,True,False,False,False,False

In [23]:
df.fillna('4',inplace=True)

In [28]:
df

,School_Category,Location_Type,Management_Type,Total_Schools,Restricted_Streams_No_Guidance,Comprehensive_Streams_With_Guidance
0,Category A,Urban,Private,1500,350,1150
1,Category B,Urban,Government,1000,650,350
2,Category C,Rural,Private,1200,720,480
3,Category D,Rural,Government,1300,1050,250
4,Total,-,Total,5000,2770,2230