In [1]:
import pandas as pd

In [2]:
import matplotlib.pyplot as plt

In [3]:
import numpy as np

In [4]:
df = pd.read_csv('data2.csv')

In [5]:
df

,Stream,Career_Path,Historical_Avg_Salary_INR,Current_Avg_Salary_INR,Projected_Future_Salary_INR,Estimated_Annual_Aspirants,Estimated_Active_Professionals,Market_Saturation_Status
0,PCB,General Physician (MBBS),360000,900000,1500000,1200000,1400000,Under-saturated / High Demand
1,PCB,Specialist Doctor (MD/MS),600000,1800000,3000000,100000,350000,Highly Under-saturated
2,PCB,Dentist (BDS),240000,450000,700000,300000,280000,Highly Saturated
3,PCB,Pharmacist (B.Pharm),180000,350000,550000,250000,600000,Saturated
4,PCB,Registered Nurse (B.Sc),150000,320000,500000,400000,1800000,Balanced Demand
5,PCB,Veterinarian (BVSc),200000,550000,850000,500000,750000,Under-saturated
6,PCB,Physiotherapist (BPT),180000,400000,650000,800000,120000,Balanced Demand
7,PCB,Medical Lab Technologist,120000,280000,420000,150000,500000,Saturated
8,PCB,Research Scientist (Microbiology),250000,600000,950000,90000,110000,Balanced Demand
9,PCB,Biotechnologist,220000,500000,800000,120000,150000,Saturated / Low Local Core Jobs
10,PCB,Ayurvedic Doctor (BAMS),180000,420000,680000,150000,400000,Balanced / Growing Demand
11,PCB,Homeopathic Doctor (BHMS),150000,380000,550000,100000,300000,Saturated
12,PCM,Mechanical Engineer,280000,550000,800000,350000,1200000,Highly Saturated
13,PCM,Civil Engineer,250000,500000,750000,400000,1500000,Highly Saturated
14,PCM,Electrical Engineer,280000,580000,850000,300000,1000000,Saturated
15,PCM,Chemical Engineer,320000,650000,1000000,80000,250000,Balanced Demand
16,PCM,Software Engineer (Core CS),360000,850000,1400000,800000,4500000,Highly Saturated at Entry Level
17,PCM,Aerospace Engineer,400000,800000,1300000,40000,60000,Under-saturated / Niche
18,PCM,Architect (B.Arch),240000,520000,800000,100000,250000,Saturated
19,PCM,Commercial Pilot,800000,2400000,3600000,15000,25000,Under-saturated / High Cost Barrier
20,PCM,Merchant Navy Officer,450000,1200000,1800000,40000,80000,Balanced Demand
21,PCM,Actuary / Statistician,350000,950000,1600000,20000,50000,Under-saturated
22,PCM,Production / Industrial Engineer,240000,480000,700000,80000,350000,Saturated
23,PCM,Geologist / Earth Scientist,300000,700000,1050000,15000,45000,Balanced Demand
24,PCMB,Biomedical Engineer,240000,500000,850000,50000,90000,Balanced Demand
25,PCM,Defense Services (Technical Entry),300000,800000,1200000,500000,60000,Highly Competitive / Under-staffed
26,PCM,Astrophysicist / Space Scientist,350000,750000,1200000,25000,15000,Niche / Low Openings
27,PCB,Nutritionist / Dietitian,140000,350000,550000,70000,110000,Balanced Demand
28,PCM,Automobile Engineer,260000,520000,780000,120000,400000,Saturated
29,PCB,Audiologist / Speech Therapist,180000,450000,720000,15000,35000,Under-saturated

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 8 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   Stream                          30 non-null     object
 1   Career_Path                     30 non-null     object
 2   Historical_Avg_Salary_INR       30 non-null     int64
 3   Current_Avg_Salary_INR          30 non-null     int64
 4   Projected_Future_Salary_INR     30 non-null     int64
 5   Estimated_Annual_Aspirants      30 non-null     int64
 6   Estimated_Active_Professionals  30 non-null     int64
 7   Market_Saturation_Status        30 non-null     object
dtypes: int64(5), object(3)
memory usage: 2.0+ KB

In [8]:
np.max(df['Historical_Avg_Salary_INR'])

800000

In [14]:
np.max(df['Projected_Future_Salary_INR']/100000)

36.0

In [39]:
df_pcb = df.loc[0:11].copy()
df_pcm  = df.loc[12:29].copy()

In [40]:
df_pcb

,Stream,Career_Path,Historical_Avg_Salary_INR,Current_Avg_Salary_INR,Projected_Future_Salary_INR,Estimated_Annual_Aspirants,Estimated_Active_Professionals,Market_Saturation_Status
0,PCB,General Physician (MBBS),360000,900000,1500000,1200000,1400000,Under-saturated / High Demand
1,PCB,Specialist Doctor (MD/MS),600000,1800000,3000000,100000,350000,Highly Under-saturated
2,PCB,Dentist (BDS),240000,450000,700000,300000,280000,Highly Saturated
3,PCB,Pharmacist (B.Pharm),180000,350000,550000,250000,600000,Saturated
4,PCB,Registered Nurse (B.Sc),150000,320000,500000,400000,1800000,Balanced Demand
5,PCB,Veterinarian (BVSc),200000,550000,850000,500000,750000,Under-saturated
6,PCB,Physiotherapist (BPT),180000,400000,650000,800000,120000,Balanced Demand
7,PCB,Medical Lab Technologist,120000,280000,420000,150000,500000,Saturated
8,PCB,Research Scientist (Microbiology),250000,600000,950000,90000,110000,Balanced Demand
9,PCB,Biotechnologist,220000,500000,800000,120000,150000,Saturated / Low Local Core Jobs
10,PCB,Ayurvedic Doctor (BAMS),180000,420000,680000,150000,400000,Balanced / Growing Demand
11,PCB,Homeopathic Doctor (BHMS),150000,380000,550000,100000,300000,Saturated

In [41]:
df.isnull()

,Stream,Career_Path,Historical_Avg_Salary_INR,Current_Avg_Salary_INR,Projected_Future_Salary_INR,Estimated_Annual_Aspirants,Estimated_Active_Professionals,Market_Saturation_Status
0,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False
12,False,False,False,False,False,False,False,False
13,False,False,False,False,False,False,False,False
14,False,False,False,False,False,False,False,False
15,False,False,False,False,False,False,False,False
16,False,False,False,False,False,False,False,False
17,False,False,False,False,False,False,False,False
18,False,False,False,False,False,False,False,False
19,False,False,False,False,False,False,False,False
20,False,False,False,False,False,False,False,False
21,False,False,False,False,False,False,False,False
22,False,False,False,False,False,False,False,False
23,False,False,False,False,False,False,False,False
24,False,False,False,False,False,False,False,False
25,False,False,False,False,False,False,False,False
26,False,False,False,False,False,False,False,False
27,False,False,False,False,False,False,False,False
28,False,False,False,False,False,False,False,False
29,False,False,False,False,False,False,False,False

In [42]:
df_pcb.groupby('Stream')['Current_Avg_Salary_INR'].agg(['mean','min','max'])

                 mean     min      max
Stream
PCB     579166.666667  280000  1800000

In [45]:
df.groupby('Stream')['Current_Avg_Salary_INR'].agg(['mean','min','max'])

                 mean     min      max
Stream
PCB     553571.428571  280000  1800000
PCM     816666.666667  480000  2400000
PCMB    500000.000000  500000   500000