In [1]:
# bad decision data and their reasons in the form of the pie chart

In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
import matplotlib.pyplot as plt

In [5]:
data = pd.read_csv('bad_stream_selection_result.csv')

In [6]:
df = pd.DataFrame(data)

In [7]:
df

,Stream / Education Choice,Failure Risk (Unemployment Rate),Regret Rate within 3 Years,The Real-World Market Reality
0,Generic Humanities / Arts Degree,15.0% - 18.0%,65.0%,High focus on rote memory; low market alignmen...
1,Generic Commerce / B.Com,10.5% - 12.0%,55.0%,Oversaturated market; plain degrees fail witho...
2,Low-Tier Science / Engineering (PCM),38.0% - 40.0% (Under Age 25),73%,Massive supply over-saturation; 5 million grad...
3,Medical / PCMB (Without NEET Selection),25.0% (NEET Dropout rate/idle),50%,Students get trapped in multiple gap years wit...
4,Vocational / Technical Diploma,3.1% - 4.2%,< 15%,Highest job-market absorption rate; severe sho...

In [8]:
df.head()

,Stream / Education Choice,Failure Risk (Unemployment Rate),Regret Rate within 3 Years,The Real-World Market Reality
0,Generic Humanities / Arts Degree,15.0% - 18.0%,65.0%,High focus on rote memory; low market alignmen...
1,Generic Commerce / B.Com,10.5% - 12.0%,55.0%,Oversaturated market; plain degrees fail witho...
2,Low-Tier Science / Engineering (PCM),38.0% - 40.0% (Under Age 25),73%,Massive supply over-saturation; 5 million grad...
3,Medical / PCMB (Without NEET Selection),25.0% (NEET Dropout rate/idle),50%,Students get trapped in multiple gap years wit...
4,Vocational / Technical Diploma,3.1% - 4.2%,< 15%,Highest job-market absorption rate; severe sho...

In [41]:
df['Regret Rate within 3 Years'] = [65,55,73,50,15] #int(df['Regret Rate within 3 Years'])

In [42]:
df.isnull()

,Stream / Education Choice,Failure Risk (Unemployment Rate),Regret Rate within 3 Years,The Real-World Market Reality
0,False,False,False,False
1,False,False,False,False
2,False,False,False,False
3,False,False,False,False
4,False,False,False,False

In [43]:
df.dropna()

,Stream / Education Choice,Failure Risk (Unemployment Rate),Regret Rate within 3 Years,The Real-World Market Reality
0,Generic Humanities / Arts Degree,16.5,65,High focus on rote memory; low market alignmen...
1,Generic Commerce / B.Com,11.0,55,Oversaturated market; plain degrees fail witho...
2,Low-Tier Science / Engineering (PCM),39.0,73,Massive supply over-saturation; 5 million grad...
3,Medical / PCMB (Without NEET Selection),25.0,50,Students get trapped in multiple gap years wit...
4,Vocational / Technical Diploma,3.5,15,Highest job-market absorption rate; severe sho...

In [44]:
# df['Failure Risk (Unemployment Rate)'] = df['Failure Risk (Unemployment Rate)'].astype(int)

In [45]:
# df['Regret Rate within 3 Years'] = df['Regret Rate within 3 Years'].astype(int)

In [46]:
# df.dtypes

In [47]:
df['Failure Risk (Unemployment Rate)'] = [16.5,11,39,25,3.5]

In [71]:
# df[1:1] = [Stream / Education Choice,	Failure Risk (Unemployment Rate),	Regret Rate within 3 Years,	The Real-World Market Reality]

#####