In [1]:
# bad decision data and their reasons in the form of the pie chart

In [2]:
import pandas as pd

In [3]:
import numpy as np

In [4]:
import matplotlib.pyplot as plt

In [5]:
data = pd.read_csv('bad_stream_selection_result.csv')

In [6]:
df = pd.DataFrame(data)

In [7]:
df

,Stream / Education Choice,Failure Risk (Unemployment Rate),Regret Rate within 3 Years,The Real-World Market Reality
0,Generic Humanities / Arts Degree,15.0% - 18.0%,65.0%,High focus on rote memory; low market alignmen...
1,Generic Commerce / B.Com,10.5% - 12.0%,55.0%,Oversaturated market; plain degrees fail witho...
2,Low-Tier Science / Engineering (PCM),38.0% - 40.0% (Under Age 25),73%,Massive supply over-saturation; 5 million grad...
3,Medical / PCMB (Without NEET Selection),25.0% (NEET Dropout rate/idle),50%,Students get trapped in multiple gap years wit...
4,Vocational / Technical Diploma,3.1% - 4.2%,< 15%,Highest job-market absorption rate; severe sho...

In [8]:
df.head()

,Stream / Education Choice,Failure Risk (Unemployment Rate),Regret Rate within 3 Years,The Real-World Market Reality
0,Generic Humanities / Arts Degree,15.0% - 18.0%,65.0%,High focus on rote memory; low market alignmen...
1,Generic Commerce / B.Com,10.5% - 12.0%,55.0%,Oversaturated market; plain degrees fail witho...
2,Low-Tier Science / Engineering (PCM),38.0% - 40.0% (Under Age 25),73%,Massive supply over-saturation; 5 million grad...
3,Medical / PCMB (Without NEET Selection),25.0% (NEET Dropout rate/idle),50%,Students get trapped in multiple gap years wit...
4,Vocational / Technical Diploma,3.1% - 4.2%,< 15%,Highest job-market absorption rate; severe sho...

In [26]:
# df['Regret Rate within 3 Years'] = int(df['Regret Rate within 3 Years'])

In [25]:
# import matplotlib.pyplot as plt
# lables = df['Stream / Education Choice']
# distribution = df['Regret Rate within 3 Years']
# plt.style.use('ggplot')
# plt.pie(distribution ,
#        labels = lables,
#        shadow = True,
#        autopct = '%1.1f%%',wedgeprops = {'edgecolor':'black','linewidht':2,'linestyle':'--'})
# plt.title('Regret Rate After 3 year with certain stream')
# plt.show()